version: '3.2'

services:

  node:
    build: .
    command: elm-live src/Main.elm -h 0.0.0.0 -p 8000 -s index.html
    ports:
      - 3000:8000
    volumes:
      - .:/mnt
      - /mnt/elm-stuff
    working_dir: /mnt